### ISSUE TITLE
Error when applying for party in LFG window

### ISSUE THREAD

**Issue by Raveout** [Foglio1024/Tera-custom-cooldowns#125]
When i try to apply for a LFG party this is what caali-proxy tells me. did i do something wrong or is there a bug somewhere? 

[12:35:53 GMT+0200] ERROR tera-proxy-game: [dispatch] write: failed to generate C_APPLY_PARTY<1>
error: no definition found for message (name: "C_APPLY_PARTY", code: null, version: undefined)
    at TeraProtocol.resolveIdentifier (C:\Users\Raveout\Desktop\Tera\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\index.js:99:13)
    at TeraProtocol.write (C:\Users\Raveout\Desktop\Tera\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\index.js:444:12)
    at Dispatch.write (C:\Users\Raveout\Desktop\Tera\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:430:26)
    at DispatchWrapper.toServer (C:\Users\Raveout\Desktop\Tera\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\dispatchWrapper.js:51:22)
    at serveApplyToLfgRequest (C:\Users\Raveout\Desktop\Tera\CaaliTeraProxy\bin\node_modules\tcc-stub\index.js:275:18)
    at Socket.<anonymous> (C:\Users\Raveout\Desktop\Tera\CaaliTeraProxy\bin\node_modules\tcc-stub\index.js:69:17)

**Comment by Foglio1024** [comment]
As said in Tera DPS discord, C_APPLY_PARTY will be released later today when Caali has time.

**Comment by Raveout** [comment]
overlooked that thank you!
