### ISSUE TITLE
Apply to Party not working

### ISSUE THREAD

**Issue by MuffinName** [Foglio1024/Tera-custom-cooldowns#133]
I can't apply to a party when using the new LFG window, proxy gives me the following error message: 
```
ERROR tera-proxy-game: [dispatch] write: failed to generate C_APPLY_PARTY<1>
error: no definition found for message (name: "C_APPLY_PARTY", code: 62961, version: undefined)
    at TeraProtocol.resolveIdentifier (C:\Users\[***]\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\index.js:99:13)
    at TeraProtocol.write (C:\Users\[***]\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\index.js:444:12)
    at Dispatch.write (C:\Users\[***]\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:430:26)
    at DispatchWrapper.toServer (C:\Users\[***]\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\dispatchWrapper.js:51:22)
    at serveApplyToLfgRequest (C:\Users\[***]\AppData\Local\Programs\CaaliTeraProxy\bin\node_modules\tcc-stub-master\index.js:275:18)
    at Socket.<anonymous> (C:\Users\[***]\AppData\Local\Programs\CaaliTeraProxy\bin\node_modules\tcc-stub-master\index.js:69:17)
```
(Username changed to [***])
Any idea what the problem is?

**Comment by Foglio1024** [comment]
Update tera-data. If you're using Caali's proxy it will be automatic.
