### ISSUE TITLE
1.1.0 update error

### ISSUE THREAD

**Issue by scarfcat** [Foglio1024/Tera-custom-cooldowns#164]
```
##### CRASH #####
End of Central Directory record could not be found.
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding)
   at TCC.UpdateManager.Update(String url) in D:\Repos\TCC\TCC.Core\UpdateManager.cs:line 265
System.IO.Compression
System.IO.InvalidDataException: End of Central Directory record could not be found.
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding)
   at TCC.UpdateManager.Update(String url) in D:\Repos\TCC\TCC.Core\UpdateManager.cs:line 265
System.Collections.ListDictionaryInternal

Void ReadEndOfCentralDirectory()
```

**Comment by Foglio1024** [comment]
Replaced zip with correct one.

**Comment by scarfcat** [comment]
New error: 
```
##### CRASH #####
Could not find file 'C:\Users\user\Downloads\TCC\tmp\TCCupdater.exe'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at TCC.UpdateManager.Update(String url) in D:\Repos\TCC\TCC.Core\UpdateManager.cs:line 268
mscorlib
System.IO.FileNotFoundException: Could not find file 'C:\Users\user\Downloads\TCC\tmp\TCCupdater.exe'.
File name: 'C:\Users\Hani\Downloads\TCC\tmp\TCCupdater.exe'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at TCC.UpdateManager.Update(String url) in D:\Repos\TCC\TCC.Core\UpdateManager.cs:line 268
System.Collections.ListDictionaryInternal

Void WinIOError(Int32, System.String)
```

**Comment by Foglio1024** [comment]
Zip replaced again.
