### ISSUE TITLE
Invisible Chat

### ISSUE THREAD

**Issue by kichakicha** [Foglio1024/Tera-custom-cooldowns#218]
Chat windows is invisible, but i somehow managed to drag one of the tabs (whispers) out of it and place it elsewhere. And then i received this error which i recovered from crash.log

##### TCC v1.2.5 - 12/01/2019 00:09:23 #####
Version: 341697 - Region: EU - Server:27
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.RoutedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at Dragablz.DragablzItem.ThumbOnDragDelta(Object sender, DragDeltaEventArgs dragDeltaEventArgs) in C:\projects\dragablz\Dragablz\DragablzItem.cs:line 541
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.Thumb.OnMouseMove(MouseEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at TCC.App.Main()
Source: mscorlib
Data: System.Collections.ListDictionaryInternal
InnerException: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at TCC.DispatcherExtensions.InvokeIfRequired(Dispatcher disp, Action dotIt, DispatcherPriority priority) in D:\Repos\TCC\TCC.Core\Utils.cs:line 338
   at System.Collections.ObjectModel.Collection`1.Remove(T item)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.RemoveItem(Int32 index)
   at TCC.SynchronizedObservableCollection`1.<>c__DisplayClass7_0.<RemoveItem>b__0() in D:\Repos\TCC\TCC.Core\Utils.cs:line 445
   at System.Collections.ObjectModel.Collection`1.Remove(T item)
   at TCC.ViewModels.ChatTabClient.TabEmptiedHandler(TabablzControl tabControl, Window window) in D:\Repos\TCC\TCC.Core\ViewModels\ChatTabClient.cs:line 24
   at Dragablz.TabablzControl.RemoveItem(DragablzItem dragablzItem) in C:\projects\dragablz\Dragablz\TabablzControl.cs:line 1113
   at Dragablz.TabablzControl.MonitorReentry(DragablzDragDeltaEventArgs e) in C:\projects\dragablz\Dragablz\TabablzControl.cs:line 1077
   at Dragablz.TabablzControl.PreviewItemDragDelta(Object sender, DragablzDragDeltaEventArgs e) in C:\projects\dragablz\Dragablz\TabablzControl.cs:line 1003
TargetSite: System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)

**Comment by kichakicha** [comment]
This issue has been fixed as of the release of v1.3.0-e version.
