### ISSUE TITLE
TODO: investigate ShowDialog() errors

### ISSUE THREAD

**Issue by Foglio1024** [Foglio1024/Tera-custom-cooldowns#233]
```
Exception has been thrown by the target of an invocation.
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
at System.Delegate.DynamicInvokeImpl(Object[] args)
at TCC.Parsing.MessageFactory.Process(ParsedMessage message) in \TCC.Core\Parsing\MessageFactory.cs L345
at TCC.Parsing.PacketAnalyzer.PacketAnalysisLoop() in \TCC.Core\Parsing\PacketAnalyzer.cs L48
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart()
mscorlib
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: ShowDialog can be called only on hidden windows.
at System.Windows.Window.ShowDialog()
at TCC.SessionManager.<>c.<InitDatabases>b__83_0() in \TCC.Core\SessionManager.cs L197
at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
at System.Windows.Threading.Dispatcher.Invoke(Action callback)
at TCC.SessionManager.InitDatabases(String lang) in \TCC.Core\SessionManager.cs L194
at TCC.Parsing.PacketHandler.HandleLogin(S_LOGIN p) in \TCC.Core\Parsing\PacketHandler.cs L170
--- End of inner exception stack trace ---
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
at System.Delegate.DynamicInvokeImpl(Object[] args)
at TCC.Parsing.MessageFactory.Process(ParsedMessage message) in \TCC.Core\Parsing\MessageFactory.cs L345
at TCC.Parsing.PacketAnalyzer.PacketAnalysisLoop() in \TCC.Core\Parsing\PacketAnalyzer.cs L48
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart()
System.Collections.ListDictionaryInternal
System.InvalidOperationException: ShowDialog can be called only on hidden windows.
at System.Windows.Window.ShowDialog()
at TCC.SessionManager.<>c.<InitDatabases>b__83_0() in \TCC.Core\SessionManager.cs L197
at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
at System.Windows.Threading.Dispatcher.Invoke(Action callback)
at TCC.SessionManager.InitDatabases(String lang) in \TCC.Core\SessionManager.cs L194
at TCC.Parsing.PacketHandler.HandleLogin(S_LOGIN p) in \TCC.Core\Parsing\PacketHandler.cs L170
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
```

**Comment by Foglio1024** [comment]
```
ShowDialog можно вызвать только для скрытых окон.
в System.Windows.Window.ShowDialog()
в TCC.Windows.TccMessageBox.<>c__DisplayClass9_0.<Show>b__0() в \TCC.Core\Windows\TccMessageBox.xaml.cs L78
в System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
в System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
в System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
в System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
в System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
в System.Windows.Threading.Dispatcher.Invoke(Action callback)
в TCC.Windows.TccMessageBox.Show(String caption, String text, MessageBoxButton button, MessageBoxImage image) в \TCC.Core\Windows\TccMessageBox.xaml.cs L80
в TCC.ViewModels.DashboardViewModel.SaveCharDoc(XDocument doc) в \TCC.Core\ViewModels\DashboardViewModel.cs L301
в TCC.Parsing.PacketAnalyzer.OnEndConnection() в \TCC.Core\Parsing\PacketAnalyzer.cs L67
в TCC.Sniffing.TeraSniffer.HandleEndConnection(TcpConnection connection) в \TCC.Core\Sniffing\TeraSniffer.cs L122
в TCC.Sniffing.TcpSniffer.Receive(IPv4Packet ipData) в \TCC.Core\Sniffing\TcpSniffer.cs L101
в TCC.Sniffing.IpSnifferWinPcap.device_OnPacketArrival(Object sender, CaptureEventArgs e) в \TCC.Core\Sniffing\IpSnifferWinPcap.cs L148
в SharpPcap.LibPcap.PcapDevice.SendPacketArrivalEvent(RawCapture p)
в SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_dispatch(IntPtr adaptHandle, Int32 count, pcap_handler callback, IntPtr ptr)
в SharpPcap.LibPcap.PcapDevice.CaptureThread()
в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
в System.Threading.ThreadHelper.ThreadStart()
PresentationFramework
System.InvalidOperationException: ShowDialog можно вызвать только для скрытых окон.
в System.Windows.Window.ShowDialog()
в TCC.Windows.TccMessageBox.<>c__DisplayClass9_0.<Show>b__0() в \TCC.Core\Windows\TccMessageBox.xaml.cs L78
в System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
в System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
в System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
в System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
в System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
в System.Windows.Threading.Dispatcher.Invoke(Action callback)
в TCC.Windows.TccMessageBox.Show(String caption, String text, MessageBoxButton button, MessageBoxImage image) в \TCC.Core\Windows\TccMessageBox.xaml.cs L80
в TCC.ViewModels.DashboardViewModel.SaveCharDoc(XDocument doc) в \TCC.Core\ViewModels\DashboardViewModel.cs L301
в TCC.Parsing.PacketAnalyzer.OnEndConnection() в \TCC.Core\Parsing\PacketAnalyzer.cs L67
в TCC.Sniffing.TeraSniffer.HandleEndConnection(TcpConnection connection) в \TCC.Core\Sniffing\TeraSniffer.cs L122
в TCC.Sniffing.TcpSniffer.Receive(IPv4Packet ipData) в \TCC.Core\Sniffing\TcpSniffer.cs L101
в TCC.Sniffing.IpSnifferWinPcap.device_OnPacketArrival(Object sender, CaptureEventArgs e) в \TCC.Core\Sniffing\IpSnifferWinPcap.cs L148
в SharpPcap.LibPcap.PcapDevice.SendPacketArrivalEvent(RawCapture p)
в SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_dispatch(IntPtr adaptHandle, Int32 count, pcap_handler callback, IntPtr ptr)
в SharpPcap.LibPcap.PcapDevice.CaptureThread()
в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
в System.Threading.ThreadHelper.ThreadStart()
System.Collections.ListDictionaryInternal
System.Nullable`1[System.Boolean] ShowDialog()
```
