### ISSUE TITLE
TODO: TaskCanceled exceptions

### ISSUE THREAD

**Issue by Foglio1024** [Foglio1024/Tera-custom-cooldowns#236]
```
Exception has been thrown by the target of an invocation.
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
at System.Delegate.DynamicInvokeImpl(Object[] args)
at TCC.Parsing.MessageFactory.Process(ParsedMessage message) in \TCC.Core\Parsing\MessageFactory.cs L350
at TCC.Parsing.PacketAnalyzer.PacketAnalysisLoop() in \TCC.Core\Parsing\PacketAnalyzer.cs L49
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart()
mscorlib
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
at System.Windows.Threading.Dispatcher.Invoke(Action callback)
at TCC.SessionManager.set_Combat(Boolean value) in \TCC.Core\SessionManager.cs L63
at TCC.Parsing.PacketHandler.HandleUserStatusChanged(S_USER_STATUS p) in \TCC.Core\Parsing\PacketHandler.cs L93
--- End of inner exception stack trace ---
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
at System.Delegate.DynamicInvokeImpl(Object[] args)
at TCC.Parsing.MessageFactory.Process(ParsedMessage message) in \TCC.Core\Parsing\MessageFactory.cs L350
at TCC.Parsing.PacketAnalyzer.PacketAnalysisLoop() in \TCC.Core\Parsing\PacketAnalyzer.cs L49
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart()
System.Collections.ListDictionaryInternal
System.Threading.Tasks.TaskCanceledException: A task was canceled.
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
at System.Windows.Threading.Dispatcher.Invoke(Action callback)
at TCC.SessionManager.set_Combat(Boolean value) in \TCC.Core\SessionManager.cs L63
at TCC.Parsing.PacketHandler.HandleUserStatusChanged(S_USER_STATUS p) in \TCC.Core\Parsing\PacketHandler.cs L93
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
```

**Comment by Foglio1024** [comment]
```
Exception has been thrown by the target of an invocation.
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
at System.Delegate.DynamicInvokeImpl(Object[] args)
at TCC.Parsing.MessageFactory.Process(ParsedMessage message) in \TCC.Core\Parsing\MessageFactory.cs L350
at TCC.Parsing.PacketAnalyzer.PacketAnalysisLoop() in \TCC.Core\Parsing\PacketAnalyzer.cs L49
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart()
mscorlib
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
at System.Windows.Threading.Dispatcher.Invoke(Action callback)
at TCC.AbnormalityManager.BeginPlayerAbnormality(Abnormality ab, Int32 stacks, UInt32 duration) in \TCC.Core\AbnormalityManager.cs L97
at TCC.AbnormalityManager.BeginAbnormality(UInt32 id, UInt64 target, UInt64 source, UInt32 duration, Int32 stacks) in \TCC.Core\AbnormalityManager.cs L66
at TCC.Parsing.PacketHandler.HandleAbnormalityBegin(S_ABNORMALITY_BEGIN p) in \TCC.Core\Parsing\PacketHandler.cs L734
--- End of inner exception stack trace ---
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
at System.Delegate.DynamicInvokeImpl(Object[] args)
at TCC.Parsing.MessageFactory.Process(ParsedMessage message) in \TCC.Core\Parsing\MessageFactory.cs L350
at TCC.Parsing.PacketAnalyzer.PacketAnalysisLoop() in \TCC.Core\Parsing\PacketAnalyzer.cs L49
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart()
System.Collections.ListDictionaryInternal
System.Threading.Tasks.TaskCanceledException: A task was canceled.
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
at System.Windows.Threading.Dispatcher.Invoke(Action callback)
at TCC.AbnormalityManager.BeginPlayerAbnormality(Abnormality ab, Int32 stacks, UInt32 duration) in \TCC.Core\AbnormalityManager.cs L97
at TCC.AbnormalityManager.BeginAbnormality(UInt32 id, UInt64 target, UInt64 source, UInt32 duration, Int32 stacks) in \TCC.Core\AbnormalityManager.cs L66
at TCC.Parsing.PacketHandler.HandleAbnormalityBegin(S_ABNORMALITY_BEGIN p) in \TCC.Core\Parsing\PacketHandler.cs L734
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
```
