### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by XelZero** [Foglio1024/Tera-custom-cooldowns#263]
[12:17:24.019] [mods] ERROR: Module "TCC" (TCC) could not be preloaded!
[12:17:24.020] [mods] ERROR: Please contact the module's author: https://github.com/Foglio1024/Tera-Custom-Cooldowns/issues
[12:17:24.021] C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox\mods\TCC\global\lib\rpc-handler.js:113
            name: params.userName
            ^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:88:7)
    at createScript (vm.js:261:10)
    at Object.runInThisContext (vm.js:309:10)
    at wrapSafe (internal/modules/cjs/loader.js:1047:15)
    at Module._compile (internal/modules/cjs/loader.js:1108:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12710)
    at Module.require (internal/modules/cjs/loader.js:1032:19)

**Comment by Foglio1024** [comment]
Fix pushed just now in 3b3f77a.
