### ISSUE TITLE
Auto update Error

### ISSUE THREAD

**Issue by Eng-RedWolf** [Foglio1024/Tera-custom-cooldowns#67]
When ever TCC try to auto update, after it finishes downloading i get an error and the error log as follow.

```
##### CRASH #####
The file 'C:\Users\Hussien\Desktop\TCC\tmp\TCC.exe' already exists.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
   at System.IO.Compression.ZipFileExtensions.ExtractToDirectory(ZipArchive source, String destinationDirectoryName)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding)
   at TCC.UpdateManager.Update(String url)
mscorlib
System.IO.IOException: The file 'C:\Users\Hussien\Desktop\TCC\tmp\TCC.exe' already exists.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
   at System.IO.Compression.ZipFileExtensions.ExtractToDirectory(ZipArchive source, String destinationDirectoryName)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding)
   at TCC.UpdateManager.Update(String url)
System.Collections.ListDictionaryInternal

Void WinIOError(Int32, System.String)
```

**Comment by Foglio1024** [comment]
Doesn't look like an update error. Are you sure that you sent me the right log? Updater errors are saved in another file.

**Comment by Eng-RedWolf** [comment]
sorry my bad didn't notice that i edit it to the right one
